### ISSUE TITLE
Not a websocket 4008 Error

### ISSUE THREAD

**Issue by Yingi** [dataprofessor/realtime-transcription#1]
Hi

After trying to run the streamlit_app.py. When i click on the Start Button. I get the following error. I have upgraded my account in AssemblyAI. Here is the Error output in my terminal

```
Connecting websocket to url $wss://api.assemblyai.com/v2/realtime/ws?sample_rate=16000
Receiving messages ...
{"message_type": "SessionBegins", "session_id": "c5029749-f61c-4540-a0b8-4f4b2426cdcb", "expires_at": "2022-11-04T14:14:36.994363"}
Sending messages ...
Connecting websocket to url $wss://api.assemblyai.com/v2/realtime/ws?sample_rate=16000
Receiving messages ...
{"message_type": "SessionBegins", "session_id": "a3e9598a-f32b-4f19-b229-1160c833546f", "expires_at": "2022-11-04T14:14:41.497725"}
Sending messages ...
sent 1000 (OK); then received 1000 (OK)
2022-11-04 07:14:42.210 Uncaught app exception
Traceback (most recent call last):
  File "/Users/acetravelstoursltd/Documents/TranscribeAI/transcribe/streamlit_app.py", line 93, in send
    data = stream.read(FRAMES_PER_BUFFER)
  File "/Users/acetravelstoursltd/Documents/TranscribeAI/lib/python3.9/site-packages/pyaudio.py", line 612, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
OSError: [Errno -9981] Input overflowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/acetravelstoursltd/Documents/TranscribeAI/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
    exec(code, module.__dict__)
  File "/Users/acetravelstoursltd/Documents/TranscribeAI/transcribe/streamlit_app.py", line 138, in <module>
    asyncio.run(send_receive())
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/acetravelstoursltd/Documents/TranscribeAI/transcribe/streamlit_app.py", line 135, in send_receive
    send_result, receive_result = await asyncio.gather(send(), receive())
  File "/Users/acetravelstoursltd/Documents/TranscribeAI/transcribe/streamlit_app.py", line 104, in send
    assert False, "Not a websocket 4008 error"
AssertionError: Not a websocket 4008 error

```

**Comment by Yingi** [comment]
> Hi
> 
> After trying to run the streamlit_app.py. When i click on the Start Button. I get the following error. I have upgraded my account in AssemblyAI. Here is the Error output in my terminal
> 
> ```
> Connecting websocket to url $wss://api.assemblyai.com/v2/realtime/ws?sample_rate=16000
> Receiving messages ...
> {"message_type": "SessionBegins", "session_id": "c5029749-f61c-4540-a0b8-4f4b2426cdcb", "expires_at": "2022-11-04T14:14:36.994363"}
> Sending messages ...
> Connecting websocket to url $wss://api.assemblyai.com/v2/realtime/ws?sample_rate=16000
> Receiving messages ...
> {"message_type": "SessionBegins", "session_id": "a3e9598a-f32b-4f19-b229-1160c833546f", "expires_at": "2022-11-04T14:14:41.497725"}
> Sending messages ...
> sent 1000 (OK); then received 1000 (OK)
> 2022-11-04 07:14:42.210 Uncaught app exception
> Traceback (most recent call last):
>   File "/Users/acetravelstoursltd/Documents/TranscribeAI/transcribe/streamlit_app.py", line 93, in send
>     data = stream.read(FRAMES_PER_BUFFER)
>   File "/Users/acetravelstoursltd/Documents/TranscribeAI/lib/python3.9/site-packages/pyaudio.py", line 612, in read
>     return pa.read_stream(self._stream, num_frames, exception_on_overflow)
> OSError: [Errno -9981] Input overflowed
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/acetravelstoursltd/Documents/TranscribeAI/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
>     exec(code, module.__dict__)
>   File "/Users/acetravelstoursltd/Documents/TranscribeAI/transcribe/streamlit_app.py", line 138, in <module>
>     asyncio.run(send_receive())
>   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/Users/acetravelstoursltd/Documents/TranscribeAI/transcribe/streamlit_app.py", line 135, in send_receive
>     send_result, receive_result = await asyncio.gather(send(), receive())
>   File "/Users/acetravelstoursltd/Documents/TranscribeAI/transcribe/streamlit_app.py", line 104, in send
>     assert False, "Not a websocket 4008 error"
> AssertionError: Not a websocket 4008 error
> ```

I Think I have seen the cause of the error.

**Comment by Yingi** [comment]
On Line 93, i added `exception_on_overflow = False`. So it worked for me.
Line 93 looks like this `data = stream.read(FRAMES_PER_BUFFER, exception_on_overflow = False)`
